/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // This tells Docusaurus to include EVERYTHING in the docs folder
    },
  ],
};

module.exports = sidebars;