/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
module.exports = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'U6 Coaching',
      items: [
        'u6/age_group_progression',
        'u6/glossary',
        'u6/parent_handout',
        'u6/curriculum/practice_plan_01_introduction_to_soccer_fun_and_basic_skills',
        'u6/curriculum/practice_plan_02_controlling_the_ball_and_first_touch',
        'u6/curriculum/practice_plan_03_passing_to_a_teammate_and_simple_rules',
        'u6/curriculum/practice_plan_04_shooting_at_a_target_and_goal_scoring',
        'u6/curriculum/practice_plan_05_teamwork_and_following_instructions',
        'u6/curriculum/practice_plan_06_basic_movement_and_agility_with_the_ball',
        'u6/curriculum/practice_plan_07_defending_your_space_and_listening_to_coach',
        'u6/curriculum/practice_plan_08_fun_games_with_a_soccer_ball',
        'u6/curriculum/practice_plan_09_dribbling_obstacle_course_spatial_awareness',
        'u6/curriculum/practice_plan_10_shooting_accuracy_simple_goalkeeping',
      ],
    },
    {
      type: 'category',
      label: 'U7 Coaching',
      items: [
        'u7/age_group_progression',
        'u7/glossary',
        'u7/curriculum/practice_plan_01_ball_familiarity_control',
        'u7/curriculum/practice_plan_02_dribbling_dynamics',
        'u7/curriculum/practice_plan_03_passing_receiving',
        'u7/curriculum/practice_plan_04_shooting_fundamentals',
        'u7/curriculum/practice_plan_05_1v1_defending',
        'u7/curriculum/practice_plan_06_spatial_awareness',
        'u7/curriculum/practice_plan_07_shielding_ball_protection',
        'u7/curriculum/practice_plan_08_spatial_awareness',
        'u7/curriculum/practice_plan_09_transition_play',
        'u7/curriculum/practice_plan_10_game_application',
      ],
    },
    {
      type: 'category',
      label: 'U8 Coaching',
      items: [
        'u8/age_group_progression',
        'u8/glossary',
        'u8/practice_plans/practice_plan_01_ball_control',
        'u8/practice_plans/practice_plan_02_dribbling_mastery',
        'u8/practice_plans/practice_plan_03_agility_direction',
        'u8/practice_plans/practice_plan_04_shooting_technique',
        'u8/practice_plans/practice_plan_05_1v1_confidence',
      ],
    },
    {
      type: 'category',
      label: 'U9 Coaching',
      items: [
        'u9/age_group_progression',
        'u9/glossary',
        'u9/curriculum/practice_plan_01_fundamental_skills_dribbling_and_control',
        'u9/curriculum/practice_plan_02_passing_accuracy_and_receiving_with_purpose',
        'u9/curriculum/practice_plan_03_shooting_techniques_and_scoring_goals',
        'u9/curriculum/practice_plan_04_basic_defensive_principles_shape_and_pressure',
        'u9/curriculum/practice_plan_05_attacking_principles_width_and_depth',
        'u9/curriculum/practice_plan_06_introduction_to_team_tactics_formations',
        'u9/curriculum/practice_plan_07_transitioning_from_defense_to_attack',
        'u9/curriculum/practice_plan_08_individual_skill_development_feints_and_moves',
        'u9/curriculum/practice_plan_09_game_understanding_positioning_and_awareness',
        'u9/curriculum/practice_plan_10_fun_small_sided_games_and_competition',
      ],
    },
    {
      type: 'category',
      label: 'U10 Coaching',
      items: [
        'u10/age_group_progression',
        'u10/glossary',
        'u10/curriculum/practice_plan_01_advanced_dribbling',
        'u10/curriculum/practice_plan_02_passing_variations',
        'u10/curriculum/practice_plan_03_shooting_accuracy_power',
        'u10/curriculum/practice_plan_04_defending_principles',
        'u10/curriculum/practice_plan_05_attacking_principles',
        'u10/curriculum/practice_plan_06_transition_play',
        'u10/curriculum/practice_plan_07_positional_play',
        'u10/curriculum/practice_plan_08_set_pieces',
        'u10/curriculum/practice_plan_09_team_shape',
        'u10/curriculum/practice_plan_10_game_intelligence',
      ],
    },
    {
      type: 'category',
      label: 'U11 Coaching',
      items: [
        'u11/age_group_progression',
        'u11/glossary',
        'u11/curriculum/practice_plan_01_dribbling_fundamentals',
        'u11/curriculum/practice_plan_02_first_touch_and_receiving',
        'u11/curriculum/practice_plan_03_shooting_accuracy',
        'u11/curriculum/practice_plan_04_passing_receiving_dynamics',
        'u11/curriculum/practice_plan_05_decision_making_awareness',
        'u11/curriculum/practice_plan_06_defensive_principles',
        'u11/curriculum/practice_plan_07_attacking_principles',
        'u11/curriculum/practice_plan_08_transition_play',
        'u11/curriculum/practice_plan_09_shooting_techniques_finishing',
        'u11/curriculum/practice_plan_10_game_scenarios_application',
      ],
    },
    {
      type: 'category',
      label: 'U12 Coaching',
      items: [
        'u12/age_group_progression',
        'u12/glossary',
        'u12/curriculum/practice_plan_01_positional_play_team_shape',
        'u12/curriculum/practice_plan_02_ball_retention_combination_play',
        'u12/curriculum/practice_plan_03_attacking_third_play_finishing',
        'u12/curriculum/practice_plan_04_defensive_organization_pressure',
        'u12/curriculum/practice_plan_05_transition_play_counter_attacking',
        'u12/curriculum/practice_plan_06_dribbling_techniques_skill_moves',
        'u12/curriculum/practice_plan_07_passing_range_vision',
        'u12/curriculum/practice_plan_08_shooting_accuracy_finishing_under_pressure',
        'u12/curriculum/practice_plan_09_defensive_pressure_compactness',
        'u12/curriculum/practice_plan_10_tactical_game_application_decision_making',
      ],
    },
    {
      type: 'category',
      label: 'US Soccer Rules',
      items: [
        'US_Soccer_Rules/birth_year_registration_guide'
      ],
    },
  ],
};